# mkinitcpio does not resolve symlinks when generating the initramfs, so make
# sure it places them in raw so that they work during boot as well.
# See https://bbs.archlinux.org/viewtopic.php?id=305089 https://bbs.archlinux.org/viewtopic.php?id=303721)
# Credit https://github.com/UtkarshVerma/dotfiles/blob/main/root/etc/mkinitcpio.conf.d/symlinks.conf
FILES+=(
    /etc/modprobe.d/*.conf
    /etc/udev/rules.d/*.rules
)
